### ISSUE TITLE
Configuration error(Extension doesn't exist on given host)

### ISSUE THREAD

**Issue by nitroxteam** [BraydenNeale/Dynatrace-SNMP#11]
When I try to add an endpoint in Dynatrace Managed the error in question is occurring.

http://prntscr.com/tj5lw2

**Comment by BraydenNeale** [comment]
Hi,

This just means that the SNMP extension is not found on your ActiveGate.

You need to copy the plugin to the ActiveGate: directory `/opt/dynatrace/remotepluginmodule/plugin_deployment`
Then restart the remotepluginmodule so that it is loaded - `systemctl restart remotepluginmodule`

**Comment by nitroxteam** [comment]
Hi Bray. 

Thanks for the quick response.
The problem was solved after your support.

I need to identify the interfaces by the field (ifDescr) apparently this is already the value used in your script to present the interfaces or am I wrong?

The interfaces are being displayed with the default name.

http://prntscr.com/tjs6fe

**Comment by BraydenNeale** [comment]
ifDescr is what's being used to identify the interfaces.
That default name is coming straight from ifDescr - 1.3.6.1.2.1.2.2.1.2
