### ISSUE TITLE
Plugin Size Too Large for Upload

### ISSUE THREAD

**Issue by GDP254** [BraydenNeale/Dynatrace-SNMP#12]
Hi,

All my recent builds of the DT-SNMP plugin, are in the range of 62 - 67 Mb while the upload size limit on both Dynatrace SaaS & Managed is 52 Mb.

How can I reduce the size of the built plugin?

**Comment by BraydenNeale** [comment]
Hi,

The plugin size should be below 10MB, unless you have added many other dependencies. The latest release is 9.84MB: https://github.com/BraydenNeale/DT-SNMP/releases/tag/1.023.

Are your builds repackaging the Zip? I have seen before that if there is already a zip file in the directory, then build had included that in the package files. So you can end up with a zip inside the zip... which would blow out the size of the plugin.

**Comment by GDP254** [comment]
Hi,

I have rebuilt the plugin from source code at the link provided and the result is 65.6 MB on the resulting zip file. 

I deleted all files in my /remotepluginmodule/plugin_deployment directory and followed the build process to the letter. 

I reviewed the resulting folder for .zip files and found none.

Note that this behavior is currently observed on Ubuntu 16.04.6 LTS (Xenial Xerus) and Oracle Linux 7. We have yet to test on other Linux distributions.

**Comment by GDP254** [comment]
Hi,

![WhatsApp Image 2020-09-02 at 12 28 38 PM](https://user-images.githubusercontent.com/3336758/92015942-3f1e2080-ed5a-11ea-86be-1cfaa5c6b80e.jpeg)

A colleague [@MamaAfrica](https://github.com/MamaAfrica), found the folders contributing to the problem by comparing your version and ours. After removing the bin, include lib and lib64 folders in the dtsnmp directory, and zipping the result the file shrunk to 14.5 MB.

I tested the plugin and it works. 

The source of the problem looks to be the packaging during the build process which includes these files that aren't necessary.

Thank you
