### ISSUE TITLE
Getting Limit Reached Error

### ISSUE THREAD

**Issue by tushargks** [BraydenNeale/Dynatrace-SNMP#16]
@BraydenNeale 
Hi Brayden

I am trying to use this plugin to configure SNMP monitoring on the routers but getting below error, could you help me on getting this fixed

**_Property sysDescr value is too long (200) for entity 1241481470268036538 EntityType.CUSTOM_DEVICE_**

**Comment by BraydenNeale** [comment]
Hi @tushargks 

This is a warning and not an error, so the monitoring and data should still be okay.
This just means the SNMP device system descriptor is longer than 200 characters - which is just a property limit length in Dynatrace. This is automatically trimmed to 200 by Dynatrace - but I could also trim in this extension to remove the warning.

Thanks,
Brayden

**Comment by tushargks** [comment]
@BraydenNeale 
Thank You! for the information
