### ISSUE TITLE
Move Config validation to class initialize function

### ISSUE THREAD

**Issue by mzball-dt** [BraydenNeale/Dynatrace-SNMP#2]
The Dynatrace ActiveGate API provides a function that is called when the plugin is initially setup with new information. 

Unless there is a specific reason to validate the config every minute, performance should be improved by doing it once when the plugin first sees the new config and then launching straight into metric gathering each minute thereafter.

This is something I'd be willing to look at given time over the next few days.

**Comment by BraydenNeale** [comment]
Thanks,
I'll refactor in the next release.

**Comment by BraydenNeale** [comment]
initialize function for config and validation added in v1.016
