### ISSUE TITLE
Multiple plugins import is not allowed. To store all plugins import them separately.

### ISSUE THREAD

**Issue by robkuehn** [BraydenNeale/Dynatrace-SNMP#4]
Hi everyone, when I try to upload, I get the following error.

> Multiple plugins import is not allowed. To store all plugins import them separately.

Our cluster is running on 1.176.131.20190918-130946.
I also tried to upload the previous plugin, but this brings another error message.

> The metricGroup field is missing. Since version 1.172, the metric group is an obligatory field. It is used for grouping custom metrics into a hierarchical namespace where various sources, for example multiple plugins, can provide data. Moreover, the metric group becomes a primary part of the metric key, which means that once defined, it must remain the same for the continuity of data. The metric group will also help you find metrics on custom charts . For more information, see:  [JSON reference] 

Thanks 
Robert

**Comment by BraydenNeale** [comment]
Hi Robert,

The build tool now just packages everything so the latest release contains a zip within a zip... I'll fix this up.

If you just upload 'plugin.json' for the latest version to the Dynatrace server it will work as expect

Thanks,
Brayden

**Comment by robkuehn** [comment]
Hi Brayden,

thank you for the fast reply. It's now working for me.

Regards,
Robert

**Comment by BraydenNeale** [comment]
Thanks for the update. I've repackaged the v1.022 zip - so this error shouldn't happen again.
