### ISSUE TITLE
[Errno -2] Name or service not knowncaused by <class 'socket.gaierror'>

### ISSUE THREAD

**Issue by mallempatisreedhar** [BraydenNeale/Dynatrace-SNMP#5]
hi Brayden,

While trying to setup the SNMP plugin am getting below Error message.

Authorisation error(Device connection issue: check snmp access: Bad IPv4/UDP transport address xxxx-xxxx.local @161: [Errno -2] Name or service not knowncaused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

Have chekced connectivity from the Gateway server to the Server from where we were trying to test the SNMP metrics and it seems it has connectivity.

Please let me know your email ID so i can share the screen shots of Connectivity and my Configuration Screen shot of AUthorisation Error.

Thanks,
Sreedhar

**Comment by BraydenNeale** [comment]
Hey,

This error means that the plugin could not resolve the hostname or IP address.
Are you able to ping that host directly from the activegate?

**Comment by mallempatisreedhar** [comment]
Thanks Brayden!

I can ping the host if i use ip. Instead of the host name i have given IP now am seeing a different message as shown below.

Authorisation error(Device connection issue: check snmp access: Wrong SNMP PDU digest)

Thanks,
Sreedhar

**Comment by BraydenNeale** [comment]
Nice,
That Wrong SNMP PDU digest error means that the credentials used were wrong.
Can you review and confirm your auth and priv keys are correct?

**Comment by BraydenNeale** [comment]
Hi Sreedhar,

I saw from the DT ticket the issue here.
instead of SHA1 and AES128, you need to put SHA and AES into the Config fields in Dynatrace.

Has to match one of the keys here.
![image](https://user-images.githubusercontent.com/11421299/70759133-63d00380-1d99-11ea-9053-17e846b86605.png)

Thanks for raising this though, I'll improve the usability on that form so that these are drop-downs in future.

Brayden

**Comment by mallempatisreedhar** [comment]
Thanks Brayden!

It works now.

Thanks,
Sreedhar

**Comment by BraydenNeale** [comment]
Enhancement for this in release 1.023. Now using dropdown fields.
https://github.com/BraydenNeale/Dynatrace-SNMP/releases/tag/1.023
