### ISSUE TITLE
Does the Dynatrace SNMP Polling Extension Plugin support Check Point 15400 firewall?

### ISSUE THREAD

**Issue by BraydenNeale** [BraydenNeale/Dynatrace-SNMP#6]
Copied from a Dynatrace support ticket.

This extension should work with checkpoint firewalls, I have previously monitored these at other customer accounts.

These metrics should be reported when the firewall is polled:
* CPU utilisation
* Memory utilisation
* Disk Utilisation
* Incoming network traffic
* Outgoing network traffic
* Incoming network errors
* Outgoing network errors

If you are wanting to poll for Firewall/Checkpoint specific metrics, you will have to add the required metrics and polling code for it. Forking this repo to a dedicated SNMP-Firewall version.

Let me know if there are any issues

**Comment by Marucoy** [comment]
Hi Brayden, 

Thanks for the explanation. 

But I am not getting use the plugin to make first polling in appliance. An error message “Authorisation error(Device connection issue: check snmp access: No SNMP response received before timeout)”. 

But when doing a snmpwlk on the same server with the same information, note that it works:
[*****@***** ~]# snmpwalk ***** ***** ******
SNMPv2-MIB::sysDescr.0 = *****
SNMPv2-MIB::sysObjectID.0 =*****
DISMAN-EVENT-MIB::sysUpTimeInstance = *****
SNMPv2-MIB::sysContact.0 = *****
SNMPv2-MIB::sysName.0 = *****
SNMPv2-MIB::sysLocation.0 = *****
SNMPv2-MIB::sysORLastChange.0 = *****
Could you help me this issue?

Regards, 
Marco Y.

**Comment by BraydenNeale** [comment]
Hi Marco,

That's odd.
That error message means that the initial connection check didn't receive a response. Usually if the host isn't whitelisted, but since you can snmpwalk that shouldn't be the case.
SNMPv2-MIB is used for the connection check (and for device properties).
```
        # Connection check and system properties
        snmpv2_mib = SNMPv2MIB(device, authentication)
        property_dict = {}
        try:
            property_dict = snmpv2_mib.poll_properties()
        except Exception as e:
            # Just report the pysnmp exception back to the end user
            info = 'Device connection issue: check snmp access'
            raise AuthException('{}: {}'.format(info,str(e))) from e
```

What version is your Activegate?
Could you also try the plugin a few times, occasionally it just gets unlucky with the first poll.

**Comment by Marucoy** [comment]
Hi Brayden, 

Thanks for update. 

I've been trying since last week without success. But today worked.
And answering your question, the version of ActiveGate is 1.181. 

Consider the issue resolved.

Thanks a lot. 

Regards, 
Marco Y.

**Comment by BraydenNeale** [comment]
Thanks for the update.
I'll look into making that initial connection check more resilient to improve this.

**Comment by Marucoy** [comment]
Hi Brayden,

 We continue with high time and many attempts at failed connections, taking up to a few days to add a new device. I believe that this is not normal.
Is there a forecast for improvement that you mentioned?

 Imagem  

 
Another question, what would be the limit of devices monitored by ActiveGate?

Regards,
Marco Y.
