### ISSUE TITLE
Authorisation error

### ISSUE THREAD

**Issue by Marucoy** [BraydenNeale/Dynatrace-SNMP#8]
Hi Brayden,

 We continue with high time and many attempts at failed connections, taking up to a few days to add a new device. I believe that this is not normal.
Is there a forecast for improvement that you mentioned?

 Imagem  

 
Another question, what would be the limit of devices monitored by ActiveGate?

Regards,
Marco Y.

_Originally posted by @Marucoy in https://github.com/BraydenNeale/Dynatrace-SNMP/issues/6#issuecomment-589122876_

**Comment by BraydenNeale** [comment]
Hi Marco,

I'm away on leave at the moment, so won't be able to look at this for a few weeks. I have seen similar timeout issues before at a large customer with many devices being polled from an AG in a different network segment.

You can get around the annoyance of adding a new device here by using the API to create it.

I'm not sure on device limits per active gate. This varies quite a lot between different environments.

Thanks,
Brayden
